In [ ]:
'''1. Classify the algorithms into supervised and unsupervised machine learning algorithms
[ Support vector machine, Decision tree, Hierarchical clustering, K-nearest neighbor, K-mean clustering, 
 Naïve Bayes, Principal component analysis, Linear discriminant analysis, independent component analysis]'''


#Supervised machine learning algorithms
Support vector machine, Decision tree, K-nearest neighbor, Naïve Bayes, Linear discriminant analysis

#unsupervised machine learning algorithms
Hierarchical clustering, K-mean clustering, Principal component analysis, independent component analysis 

In [ ]:
'''2. Given a data set, we are going to see how feature extraction can be done. Electric motor drive data set is given. 
(electric_motor.csv).

Steps for feature extraction
 
(a) Load the data into the variable explorer'''

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('electric_motor.csv')
df

ambient   coolant       u_d       u_q  motor_speed    torque  \
0      -0.752143 -1.118446  0.327935 -1.297858    -1.222428 -0.250182   
1      -0.771263 -1.117021  0.329665 -1.297686    -1.222429 -0.249133   
2      -0.782892 -1.116681  0.332771 -1.301822    -1.222428 -0.249431   
3      -0.780935 -1.116764  0.333700 -1.301852    -1.222430 -0.248636   
4      -0.774043 -1.116775  0.335206 -1.303118    -1.222429 -0.248701   
...          ...       ...       ...       ...          ...       ...   
998065 -0.047497  0.341638  0.331475 -1.246114    -1.222428 -0.255640   
998066 -0.048839  0.320022  0.331701 -1.250655    -1.222437 -0.255640   
998067 -0.042350  0.307415  0.330946 -1.246852    -1.222430 -0.255640   
998068 -0.039433  0.302082  0.330987 -1.249505    -1.222432 -0.255640   
998069 -0.043803  0.312666  0.330830 -1.246590    -1.222431 -0.255640   

             i_d       i_q        pm  stator_yoke  stator_tooth  \
0       1.029572 -0.245860 -2.522071    -1.831422     -2.066143   
1       1.029509 -0.245832 -2.522418    -1.830969     -2.064859   
2       1.029448 -0.245818 -2.522673    -1.830400     -2.064073   
3       1.032845 -0.246955 -2.521639    -1.830333     -2.063137   
4       1.031807 -0.246610 -2.521900    -1.830498     -2.062795   
...          ...       ...       ...          ...           ...   
998065  1.029142 -0.245723  0.429853     1.018568      0.836084   
998066  1.029148 -0.245736  0.429751     1.013416      0.834438   
998067  1.029191 -0.245701  0.429439     1.002906      0.833936   
998068  1.029147 -0.245727  0.429558     0.999157      0.830504   
998069  1.029141 -0.245722  0.429166     0.987163      0.828046   

        stator_winding  profile_id  
0            -2.018033           4  
1            -2.017631           4  
2            -2.017343           4  
3            -2.017632           4  
4            -2.018145           4  
...                ...         ...  
998065        0.494725          72  
998066        0.494279          72  
998067        0.492666          72  
998068        0.490581          72  
998069        0.489382          72  

[998070 rows x 13 columns]

In [3]:
df.isnull().sum()

ambient           0
coolant           0
u_d               0
u_q               0
motor_speed       0
torque            0
i_d               0
i_q               0
pm                0
stator_yoke       0
stator_tooth      0
stator_winding    0
profile_id        0
dtype: int64

In [4]:
df.shape

(998070, 13)

In [5]:
df.duplicated().sum()

0

In [6]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1

outliers=df[(df < (Q1 - 1.5 *IQR)) | (df > (Q3 + 1.5 *IQR)) ]
outliers.isnull().sum()

ambient           959578
coolant           998070
u_d               980020
u_q               998070
motor_speed       998070
torque            870767
i_d               998070
i_q               849535
pm                996569
stator_yoke       998070
stator_tooth      998070
stator_winding    998070
profile_id        998070
dtype: int64

In [7]:
df1=df[~((df < (Q1 - 1.5 *IQR)) | (df > (Q3 + 1.5 *IQR))).any(axis=1)]
df1.shape

(814996, 13)

In [8]:
df2=df.drop(['torque'],axis=1)
df2

ambient   coolant       u_d       u_q  motor_speed       i_d  \
0      -0.752143 -1.118446  0.327935 -1.297858    -1.222428  1.029572   
1      -0.771263 -1.117021  0.329665 -1.297686    -1.222429  1.029509   
2      -0.782892 -1.116681  0.332771 -1.301822    -1.222428  1.029448   
3      -0.780935 -1.116764  0.333700 -1.301852    -1.222430  1.032845   
4      -0.774043 -1.116775  0.335206 -1.303118    -1.222429  1.031807   
...          ...       ...       ...       ...          ...       ...   
998065 -0.047497  0.341638  0.331475 -1.246114    -1.222428  1.029142   
998066 -0.048839  0.320022  0.331701 -1.250655    -1.222437  1.029148   
998067 -0.042350  0.307415  0.330946 -1.246852    -1.222430  1.029191   
998068 -0.039433  0.302082  0.330987 -1.249505    -1.222432  1.029147   
998069 -0.043803  0.312666  0.330830 -1.246590    -1.222431  1.029141   

             i_q        pm  stator_yoke  stator_tooth  stator_winding  \
0      -0.245860 -2.522071    -1.831422     -2.066143       -2.018033   
1      -0.245832 -2.522418    -1.830969     -2.064859       -2.017631   
2      -0.245818 -2.522673    -1.830400     -2.064073       -2.017343   
3      -0.246955 -2.521639    -1.830333     -2.063137       -2.017632   
4      -0.246610 -2.521900    -1.830498     -2.062795       -2.018145   
...          ...       ...          ...           ...             ...   
998065 -0.245723  0.429853     1.018568      0.836084        0.494725   
998066 -0.245736  0.429751     1.013416      0.834438        0.494279   
998067 -0.245701  0.429439     1.002906      0.833936        0.492666   
998068 -0.245727  0.429558     0.999157      0.830504        0.490581   
998069 -0.245722  0.429166     0.987163      0.828046        0.489382   

        profile_id  
0                4  
1                4  
2                4  
3                4  
4                4  
...            ...  
998065          72  
998066          72  
998067          72  
998068          72  
998069          72  

[998070 rows x 12 columns]

In [9]:
#(b) Construct covariance matrix

In [10]:
x=df2.iloc[:,0:12].values
x

array([[-7.5214297e-01, -1.1184461e+00,  3.2793520e-01, ...,
        -2.0661428e+00, -2.0180326e+00,  4.0000000e+00],
       [-7.7126324e-01, -1.1170206e+00,  3.2966480e-01, ...,
        -2.0648587e+00, -2.0176313e+00,  4.0000000e+00],
       [-7.8289163e-01, -1.1166813e+00,  3.3277150e-01, ...,
        -2.0640730e+00, -2.0173435e+00,  4.0000000e+00],
       ...,
       [-4.2350100e-02,  3.0741498e-01,  3.3094567e-01, ...,
         8.3393570e-01,  4.9266600e-01,  7.2000000e+01],
       [-3.9433220e-02,  3.0208160e-01,  3.3098695e-01, ...,
         8.3050430e-01,  4.9058100e-01,  7.2000000e+01],
       [-4.3802520e-02,  3.1266590e-01,  3.3082953e-01, ...,
         8.2804570e-01,  4.8938242e-01,  7.2000000e+01]])

In [11]:
y=df.iloc[:,5].values
y

array([-0.2501821 , -0.2491333 , -0.24943107, ..., -0.25563973,
       -0.25563973, -0.25563973])

In [12]:
cov_matrix = np.cov(x, rowvar=False)
cov_matrix

array([[ 9.86300805e-01,  4.32494787e-01,  1.93005042e-01,
         8.70310410e-02,  7.78404221e-02,  5.56047815e-03,
        -2.58230851e-01,  4.95900999e-01,  4.48982998e-01,
         3.93856595e-01,  2.99311687e-01,  8.43019799e+00],
       [ 4.32494787e-01,  1.00485264e+00,  1.78761322e-01,
         2.79838454e-02, -3.34533704e-02,  1.08642049e-01,
        -1.86121348e-01,  4.29729580e-01,  8.77074028e-01,
         6.90395090e-01,  5.09685941e-01,  1.10559849e+01],
       [ 1.93005042e-01,  1.78761322e-01,  9.95760865e-01,
        -2.74776268e-02, -2.33618909e-01,  3.57396729e-01,
        -7.93236133e-01, -8.20336287e-02,  4.13838061e-02,
        -6.60889658e-02, -1.50144593e-01,  6.62486546e+00],
       [ 8.70310410e-02,  2.79838454e-02, -2.74776268e-02,
         1.00466581e+00,  7.19451323e-01, -1.82095355e-01,
        -2.63547055e-02,  1.01033848e-01,  1.06545596e-01,
         1.49304332e-01,  1.25529272e-01, -2.70494308e+00],
       [ 7.78404221e-02, -3.34533704e-02, -2.3361890

In [13]:
#(c) Find Eigen values and Eigen vectors of the matrix

In [14]:
from numpy.linalg import eigh
eigenvalues, eigenvectors = eigh(cov_matrix)

In [15]:
eigenvalues

array([8.25481143e-04, 8.03924883e-03, 4.06345431e-02, 1.37192014e-01,
       2.43020757e-01, 3.56147063e-01, 7.21703462e-01, 8.35582229e-01,
       1.57203564e+00, 1.87599498e+00, 4.27157403e+00, 4.88137349e+02])

In [16]:
eigenvectors

array([[ 7.60458664e-04, -5.05174710e-03,  5.23419617e-02,
        -1.11158470e-01,  1.78986998e-01, -4.00754552e-01,
        -8.19026209e-01,  1.38480295e-01, -6.26234075e-02,
        -2.52417397e-01, -1.85254436e-01,  1.73579108e-02],
       [-1.23808916e-01, -4.06417039e-01, -1.09091810e-01,
         2.91287416e-01, -4.19184951e-01, -4.20424334e-01,
         2.59072966e-01,  3.45613192e-01,  1.94970533e-01,
        -2.85613669e-01, -2.52190850e-01,  2.27669793e-02],
       [-6.04991952e-03,  7.76892919e-03,  1.40743624e-01,
         5.26853008e-01,  4.71070814e-01, -4.50281881e-02,
         1.90877715e-01, -2.11775172e-01, -3.04196155e-01,
        -5.40049526e-01,  1.13699000e-01,  1.36254984e-02],
       [-5.51346630e-03, -1.92725513e-02, -4.25640898e-01,
        -6.39408229e-02,  2.35813520e-01,  1.66108676e-01,
         1.01130215e-01,  5.95845172e-01, -5.71298158e-01,
         1.06801810e-01, -1.67516290e-01, -5.54529954e-03],
       [ 3.63496014e-02, -1.72907861e-02,  6.8284115

In [17]:
#(d) Arrange the Eigen values and Eigen vectors in descending order

In [18]:
total_eigenvalues = sum(eigenvalues)
var_exp = [(i/total_eigenvalues) for i in sorted(eigenvalues, reverse=True)]
var_exp

[0.9798017915368882,
 0.00857401282062106,
 0.0037655451794878607,
 0.003155430202244406,
 0.0016772020542469427,
 0.0014486216754505744,
 0.0007148675081136023,
 0.0004877974884677463,
 0.0002753753255294423,
 8.156269587767111e-05,
 1.6136586177144224e-05,
 1.6569268954470877e-06]

In [19]:
#(e) Select the number of Eigen values such that the ration of selected and total Eigen values is 0.95.

In [20]:
sum2=0
for i in var_exp:
    sum2+=i
    print(i)
    if sum2>=0.95:
        print('total Eigen values is >= 0.95 : ',sum2)
        break

0.9798017915368882
total Eigen values is >= 0.95 :  0.9798017915368882


In [ ]:
#(f) After doing this select as many Eigen vector as number of Eigen values selected.

In [21]:
egnpairs = [(np.abs(eigenvalues[0]), (eigenvectors[:, 1]))]
projectionMatrix = np.hstack((egnpairs[0][1][:, np.newaxis]))

In [22]:
projectionMatrix

array([-5.05174710e-03, -4.06417039e-01,  7.76892919e-03, -1.92725513e-02,
       -1.72907861e-02, -9.06791950e-02,  1.09461670e-02, -5.96751355e-02,
        6.40010575e-01,  2.61553516e-01, -5.86635725e-01,  4.52269586e-05])